### ISSUE TITLE
Specifying username and password via env does not work

### ISSUE THREAD

**Issue by Hayao0819** [BrenekH/blinky#38]
```yml
version: "2.4"
services:
  blinky:
    image: ghcr.io/brenekh/blinky:master
    environment:
      - BLINKY_REPO_PATH="/repos/myrepo"
      - BLINKY_API_UNAME="hayao"
      - BLINKY_API_PASSWD="mypassword"
    volumes:
      - ./data:/data:rw
      - ./repos:/repos:rw
    ports:
      - 9000:9000
    restart: unless-stopped
```

I created this compose file, but endpoint returns 401 error.

Something seems to be preventing the credentials from being set up correctly.

**Comment by BrenekH** [comment]
It took me a little bit to figure out the problem, but it's actually pretty simple. When specifying environment variables in a `docker-compose.yaml` you can't use double quotes `"` to encapsulate the value of the env var, the quotes become a part of the value passed.

In your case, the username is not `hayao`, but rather `"hayao"` and the password is not `mypassword` but `"mypassword"`.

Changing to this yaml definition works as expected:

```yaml
services:
  blinky:
    image: ghcr.io/brenekh/blinky:master
    environment:
      - BLINKY_REPO_PATH=/repos/myrepo
      - BLINKY_API_UNAME=hayao
      - BLINKY_API_PASSWD=mypassword
    volumes:
      - ./data:/data:rw
      - ./repos:/repos:rw
    ports:
      - 9000:9000
    restart: unless-stopped
```
